# See tutorial:
#   https://michaelcurrin.github.io/code-cookbook/recipes/ci-cd/github-actions/workflows/node/upgrade-packages.html
name: Update dependencies

on:
  schedule:
    # https://crontab.guru/#0_8_*_*_1
    - cron: '0 8 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-packages:
    name: Update npm packages

    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v3

      - name: âš™ï¸ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: â¬‡ï¸ Install dependencies
        run: npm ci

      - name: ğŸ” Check for outdated packages
        id: vars
        run: |
          OUTDATED=$(npm outdated) || true

          delimiter="$(openssl rand -hex 8)"
          echo "outdated_result<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "$OUTDATED" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

          if [[ -z "$OUTDATED" ]]; then
            echo 'Nothing to update' >> "${GITHUB_STEP_SUMMARY}"
            echo "outdated=false" >> "${GITHUB_OUTPUT}"
          else
            echo 'Found outdated packages:' >> "${GITHUB_STEP_SUMMARY}"
            echo '```' >> "${GITHUB_STEP_SUMMARY}"
            echo $OUTDATED >> "${GITHUB_STEP_SUMMARY}"
            echo '```' >> "${GITHUB_STEP_SUMMARY}"
            echo "outdated=true" >> "${GITHUB_OUTPUT}"
          fi

      - name: â« Update packages
        id: update
        if: ${{ steps.vars.outputs.outdated }}
        run: |
          npm update --save
          echo "diff_result=$(git diff package.json | grep "^+\s")" >> "${GITHUB_OUTPUT}"

      # - name: ğŸ§ Lint
      #   if: ${{ steps.vars.outputs.outdated }}
      #   run: npm lint:check

      # - name: ğŸš¨ Test
      #   if: ${{ steps.vars.outputs.outdated }}
      #   run: npm test:unit

      - name: ğŸ—ï¸ Build
        if: ${{ steps.vars.outputs.outdated }}
        run: npm run build
        env:
          NODE_ENV: production

      - name: ğŸ”€ Commit and create PR
        if: ${{ steps.vars.outputs.outdated }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          title: 'build(deps): update NPM packages (automated)'
          body: |
            # Updating dependencies

            ```
            ${{ steps.update.outputs.diff_result }}
            ```

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: 'build-deps-update-npm-packages-automated'
          delete-branch: true
          commit-message: 'build(deps): update NPM packages (automated)'
          labels: |
            type: dependencies ğŸ”—
            automerge ğŸ¤
