# See tutorial:
#   https://michaelcurrin.github.io/code-cookbook/recipes/ci-cd/github-actions/workflows/node/upgrade-packages.html
name: Update dependencies

on:
  schedule:
    # https://crontab.guru/#0_8_*_*_1
    - cron: '0 8 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-packages:
    name: Update npm packages

    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v3

      - name: âš™ï¸ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: â¬‡ï¸ Install dependencies
        run: npm ci

      - name: ğŸ” Check for outdated packages
        id: vars
        run: |
          OUTDATED=$(npm outdated || true)

          if [[ -z "$OUTDATED" ]]; then
            echo 'Nothing to update' >> "${GITHUB_STEP_SUMMARY}"
            echo "updatable=false" >> "${GITHUB_OUTPUT}"
          else
            HEADER=$(echo "$OUTDATED" | grep "Package")
            COMPATIBLE=$(echo "$OUTDATED" | awk '$2!=$3' | grep -v "Package")
            if [[ -z "$COMPATIBLE" ]]; then
              COMPATIBLE_COUNT=0
            else
              COMPATIBLE_COUNT=$(($(echo "$COMPATIBLE" | wc -l) + 0))
            fi
            NOT_COMPATIBLE=$(echo "$OUTDATED" | awk '$2==$3')
            if [[ -z "$NOT_COMPATIBLE" ]]; then
              NOT_COMPATIBLE_COUNT=0
            else
              NOT_COMPATIBLE_COUNT=$(($(echo "$NOT_COMPATIBLE" | wc -l) + 0))
            fi

            if [[ $COMPATIBLE_COUNT -gt 0 ]]; then
              {
                echo "${COMPATIBLE_COUNT} package(s) will be updated:"
                echo '```'
                echo "${HEADER}"
                echo "${COMPATIBLE}"
                echo '```'
              } >> "${GITHUB_STEP_SUMMARY}"
              echo "updatable=true" >> "${GITHUB_OUTPUT}"
            else
              echo 'Nothing to update' >> "${GITHUB_STEP_SUMMARY}"
              echo "updatable=false" >> "${GITHUB_OUTPUT}"
            fi

            if [[ $NOT_COMPATIBLE_COUNT -gt 0 ]]; then
              {
                echo ''
                echo "${NOT_COMPATIBLE_COUNT} not compatible update(s):"
                echo '```'
                echo "${HEADER}"
                echo "${NOT_COMPATIBLE}"
                echo '```'
              } >> "${GITHUB_STEP_SUMMARY}"
            fi
          fi

      - name: â« Update packages
        id: update
        if: ${{ steps.vars.outputs.updatable }}
        run: |
          npm update --save

          delimiter2="$(openssl rand -hex 8)"
          echo "diff_result<<${delimiter2}" >> "${GITHUB_OUTPUT}"
          echo "$(git diff package.json | grep -e "^[-+]\s")" >> "${GITHUB_OUTPUT}"
          echo "${delimiter2}" >> "${GITHUB_OUTPUT}"

      # - name: ğŸ§ Lint
      #   if: ${{ steps.vars.outputs.updatable }}
      #   run: npm lint:check

      # - name: ğŸš¨ Test
      #   if: ${{ steps.vars.outputs.updatable }}
      #   run: npm test:unit

      - name: ğŸ—ï¸ Build
        if: ${{ steps.vars.outputs.updatable }}
        run: npm run build
        env:
          NODE_ENV: production

      - name: ğŸ”€ Commit and create PR
        if: ${{ steps.vars.outputs.updatable }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          title: 'build(deps): update NPM packages [skip ci]'
          body: |
            # Updating dependencies

            ```
            ${{ steps.update.outputs.diff_result }}
            ```

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: 'update-dependencies'
          delete-branch: true
          commit-message: 'build(deps): update NPM packages [skip ci]'
          labels: |
            type: dependencies ğŸ”—
            automerge ğŸ¤
